Apuntes
0. Instalar AppServ v 8.4.0 (PHP 5.6 y 7.0) en https://www.appserv.org/en/download/
1. Seleccionar PHP version 7.0.xx
2. En la Carpeta que se cree del AppServ se ingresa a la php7 y se reemplaza el php.ini que existan por el que esta en la ubicación de este archivo
3. Reiniciar APache 
4. Se debe importar la BD, que tambien esta en la carpeta de soporte.
5. Solo se puede ingresar al juego con los jugadores que existe en la BD.
6. Se exporto la BD MySql solo se debe importar
7. La configuracion de conexion esta en un archico que se llama config.php en la ruta preguntas\class
8. Listo